### PR TITLE
safe guard for memory error

### PR DESCRIPTION
**Pull request by pb-jchin**

### CODE REVIEW

**Comment by pb-jchin** [comment]
Used this new code for NIST Trio Child assembly. It works on-par with the previous version but with much better I/O performance and less useless computation during the consensus stage. I am merging the code.

**Comment by pb-cdunn** [comment]
No objection here. I don't fully understand the change, so I didn't comment.

**Comment by pb-jchin** [comment]
The change is to reduce the amount of sequence data that LA4Falcon to fetch and send to the consensus code. The basic problem is that when one seqences large or very repetitive genomes, sometimes there are many false positive hits. For example, you can find some reads have more 50,000 reads aligned. They can't be all from  the same genomic location. The idea is to use some simple predictor (overlap length - overhang length used here) to select those that have higher likelihood to be from the same genomic location and limit the total amount of sequences to fetch and ouput. This may solve some I/O bandwidth issue and if the predictor is good, the results could be even better in theory.  With this change, I was able to have 120 concurrent I/O proceses reading the `.raw_read.bps` and feed to the computation to utilize the CPUs with about 10% sys call overheads and some even smaller i/o wait. The older code will waste a lot of time on the `lseek` sys calls as the code has to fetch many sequences even most of them are not used at the end.

Also, ideally, I would use a priority queue to keep the top n-hits. It could be done later. The flat array + qsort solve the current problem.

**Comment by pb-jchin** [comment]
oh. the MIN macro was not used at the end. we can remove it.

**Comment by pb-cdunn** [comment]
Nice.

> Also, ideally, I would use a priority queue to keep the top n-hits. It could be done later.

Maybe I'll try that myself someday.

**Pull request merged**
